spring:
  application:
    name: 20-SB-Actuators-App
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans
  endpoint:
    shutdown:
      access: unrestricted
