spring:
  application:
    name: 23-SB-Welcome-API
  boot:
    admin:
      client:
        url: http://localhost:1111/   # Admin server url
    
#server:
#  port: 8081
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/   if eureka server port is diff then it will use.


# enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
   